version: '3.4'

services:
  app:
    image: kontinu/docker-k8s-101:${TAG:-v0.0}
    environment:
      - FOO="from compose"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000

