version: '3'

services:
  # middleware
  app:
    image: kontinu/docker-k8s-101:${TAG:-v0.0}
    environment:
      - FOO=from compose $OUT
      - REDIS_HOST=db
      - DOCKER_SERVICE_NAME={{.Service.Name}}.{{.Task.Slot}}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${HTTP_PORT:-5000}:5000
    deploy:
      replicas: 5
    # logging:
    #   driver: awslogs
    #   options:
    #     awslogs-group: ec2-tutorial
    #     awslogs-region: us-west-2
    #     awslogs-stream-prefix: web
  # data tier


