apiVersion: apps/v1
kind: Deployment
metadata:
  name:  kontinu-app
  labels:
    name:  kontinu-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kontinu-app
  template: # PodTemplate
    metadata:
      labels:
        app: kontinu-app
    spec:
      containers:
      - image:  kontinu/docker-k8s-101:v0.0
        name:  kontinu-app
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 5000
        #   initialDelaySeconds: 90
        #   timeoutSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 5000
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 10
        env:
        - name:  FOO
          value:  hello from kubernetes
        ports:
        - containerPort:  5000
          name:  web

      restartPolicy: Always


---
kind: Service
apiVersion: v1
metadata:
  name:  kontinu-app
spec:
  selector:
    app: kontinu-app
  type:  LoadBalancer
  ports:
  - name:  web
    port:  80
    targetPort:  5000